package com.TwentyFourTech.brainlimits.Fragment;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.TwentyFourTech.brainlimits.R;
import com.TwentyFourTech.brainlimits.model.ModelSoal;
import com.TwentyFourTech.brainlimits.adapter.AdapterSoal;

import java.util.ArrayList;
import java.util.List;

public class FragmentSoal extends Fragment {

     View v;

     private android.support.v7.widget.RecyclerView myrecyclerview;
     private List<ModelSoal> IstContact;

     public FragmentSoal() {
     }

     @Nullable
     @Override
     public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

          v = inflater.inflate(R.layout.fragment_soal,container,false);
          myrecyclerview = (RecyclerView) v.findViewById(R.id.contact_recyclerview);
          AdapterSoal adapterSoal = new AdapterSoal(getContext(), IstContact);
          myrecyclerview.setLayoutManager(new LinearLayoutManager(getActivity()));
          myrecyclerview.setAdapter(adapterSoal);
          return v;
     }

     @Override
     public void onCreate(@Nullable Bundle savedInstanceState) {
          super.onCreate(savedInstanceState);

          IstContact = new ArrayList<>();
          IstContact.add(new ModelSoal("MATEMATIKA","Grafik fungsi y = (m -3) x2 + 4x - 2m merupakan fungsi definit negatif. Batas-batas nilai m yang memenuhi adalah....","a. m < 3","b. m > 3", "c. 1 < m < 2","d. 1 < m < 3",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("MATEMATIKA","Toko A, toko B, dan toko C menjual sepeda. Ketiga toko tersebut selalu berbelanja di sebuah distributor sepeda yang sama. Toko A harus membayar Rp5.500.000,00 untuk pembelian 5 sepeda jenis I dan 4 sepeda jenis II. Toko B harus membayar Rp3.000.000,00 untuk pembelian 3 sepeda jenis I dan 2 sepeda jenis II. Jika toko C membeli 6 sepeda jenis I dan 2 sepeda jenis II, maka toko C harus membayar….","a. Rp3.500.000,00","b. Rp4.000.000,00", "c. Rp4.500.000,00 ","d. Rp5.000.000,00",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("MATEMATIKA","Suatu usaha kecil menengah tas dan sepatu, mempunyai bahan baku kulit dan plastik masing-masing 4500 cm2. Untuk membuat sebuah sepatu diperlukan bahan kulit 30cm2 dan bahan plastik 15cm2. Untuk membuat sebuah tas diperlukan bahan kulit 15cm2 dan bahan plastik 30cm2. Jika keuntungan sebuah sepatu sama dengan keuntungan sebuah tas, maka usaha kecil menengah tersebut akan mendapat keuntungan maksimum, jika dibuat....","a. 150 buah tas saja","b. 150 buah sepatu saja", "c. 100 tas dan 100 sepatu","d. 150 tas dan 100 sepatu",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("MATEMATIKA","Harga tiket kelas I dalam final Piala Presiden 2018 adalah Rp500.000,00. Panitia menyediakan 8 baris untuk kelas I, dengan rincian pada baris pertama terdapat 8 kursi, baris kedua 10 kursi, pada baris ketiga 12 kursi dan seterusnya. Jika kursi terisi semua pada kelas tersebut, maka pendapatan yang diterima dari kelas I adalah....","a. Rp60.000.000,00","b. Rp70.000.000,00", "c. Rp80.000.000,00","d. Rp85.000.000,00",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("MATEMATIKA","Garis y = – 3x + 1 diputar sebesar 900 berlawanan dengan arah jarum jam dengan pusat (0,0) kemudian hasilnya dicerminkan terhadap sumbu x. Persamaan bayangannya adalah….","a. – x + 3y = 1","b. x – 3y = 1", "c. – x – 3y = 1","d. – x – y = 1",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("FISIKA","Sebuah pesawat terbang bergerak ke arah Utara sejauh 13 km kemudianberbelok ke arah Timur sejauh 24 km dan berbelok lagi ke arah Selatan sejauh 3 km. Tentukan perpindahan yang dialami pesawat terbang!","A. 23 km","B. 24 km", "C. 25 km","D. 26 km",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("FISIKA","Benda bermassa 2 kg bergerak secara beraturan dalam lintasan melingkar berjari-jari 0,5 m dengan kecepatan 4 m/s. Perhatikan pernyataan berikut.\n" + "\n" + "1. Gaya sentripetalnya 64 N\n" + "2. Percepatan sentripetalnya 32 m/s2\n" + "3. Kecepatan sudutnya 8 rad/s\n" + "Pernyataan yang benar terkait kasus diatas adalah....","A. 1), 2), dan 3)","B. 1) dan 2)", "C. 1) dan 3)","D. 2) dan 3)",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("FISIKA","Sebuah benda jatuh bebas dari ketinggian 20 meter, benda tersebut memiliki energi kinetik awal sebesar 40 joule. Berapakah kecepatan benda pada ketinggian 10 meter jika massa benda tersebut 1 kg? (g = 10 m/s2)","A. 2v70 m/s","B. 3v70 m/s", "C. 4v70 m/s","D. 5v70 m/s",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("FISIKA","Bola pingpong bermassa 5 gram jatuh bebas dari ketinggian tertentu (g = 10 m/s2). Ketika menumbuk lantai kecepatan bola 6 m/s dan sesaat setelah menumbuk lantai, bola terpantul ke atas dengan kecepatan 4 m/s. Besar impuls yang bekerja pada bola pingpong adalah ... Ns","A. 0,01","B. 0,02", "C. 0,03","D. 0,05",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("FISIKA","Bola A bergerak ke arah kanan, kemudian bertumbukan dengan bola B yang bergerak ke kiri dengan kecepatan 2 m/s. Kedua benda saling menempel satu sama lain dan memiliki nilai kecepatan setelah tumbukan sebesar 3 m/s ke kanan. Jika massa bola A 25 gram dan massa bola B 30 gram, maka kecepatan bola A sebelum tumbukan adalah ... m/s.","A. 3","B. 5", "C. 6","D. 9",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("KIMIA","Perhatikan konfigurasi elektron di bawah ini!\n" + "\n" + "Y : [Ne]3s^23p^5\n" + "\n" + "Dari konfigurasi elektron di atas, dapat disimpulkan bahwa unsur Y berada pada....","A. periode 3, golongan VIIA","B. periode 3, golongan VIIB", "C. periode 3, golongan VA","D. periode 5, golongan IIIA",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("KIMIA","Pernyataan yang benar mengenai sifat koligatif larutan elektrolit dan nonelektrolit dengan molalitas yang sama adalah....","A. titik didih larutan elektrolit lebih rendah dibanding larutan nonelektrolit","B. titik beku larutan elektrolit lebih rendah dibanding larutan nonelektrolit", "C. titik didih larutan elektrolit sama dengan titik didih larutan nonelektrolit","D. tekanan uap larutan elektrolit lebih tinggi dibandingkan larutan nonelektrolit",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("KIMIA","Suatu zat X jika direaksikan dengan pereaksi Fehling terbentuk endapan merah bata. Maka zat X tersebut kemungkinan mengandung....","A. selulosa","B. sukrosa", "C. amilum","D. fruktosa",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("KIMIA","Dalam reaksi BF3 + NH3 ? NH3BF3, BF3 bertindak sebagai….","A. basa Bronsted-Lowry","B. basa Lewis", "C. asam Lewis","D. asam Bronsted-Lowry",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("KIMIA","Sebanyak 100ml CaCl2 0.6M dicampur dengan 100ml Na2CO3 0.6M. jika Ksp CaCO3 = 2.8 x 10 -9, massa zat yang mengendap adalah.... (Ar. Ca = 40, C = 12, O = 16, Na = 23, Cl = 35.5)","A. 6 gram","B. 9 gram", "C. 60 gram","D. 100 gram",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BIOLOGI","Perhatikan ciri-ciri makhluk hidup berikut ini !\n" + "\n" + "1. Eukariot\n" + "2. Heterotrof\n" + "3. Pencernaan ekstraseluler\n" + "4. Tidak memiliki klorofil\n" + "5. Dinding sel tersusun atas kitin\n" + "Peranan organisme yang memiliki ciri di atas dalam ekosistem adalah.....","A. konsumen","B. produsen", "C. dekomposer","D. detritivor",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BIOLOGI","Pencemaran lingkungan dapat ditimbulkan oleh berbagai bahan pencemar, salah satunya adalah penumpukan kotoran dari peternakan. Cara mengatasi bahan pencemar itu sehingga menjadi bermanfaat bagi manusia adalah....","A. mengeringkan dan memadatkannya sebagai bahan bakar","B. menampung dan memprosesnya menjadi biogas", "C. mengolahnya menjadi makanan ternak","D. memanfaatkannya untuk industri kertas",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BIOLOGI","Pada sebuah percobaan perkecambahan, biji kacang merah ditanam dalam pot yang berbeda yaitu pot A dan B. Pot A ditanam biji kacang merah dengan pemberian air 10 ml perhari, sedangkan pot B ditanam biji kacang merah dengan pemberian air 25 ml perhari. Setelah didiamkan selama 5 hari kondisi pot A mulai tumbuh kecambah dan pot B tidak tumbuh kecambah. Berdasarkan percobaan di atas dapat disimpulkan bahwa....","A. pemberian air tidak mempengaruhi proses perkecambahan","B. air yang terlalu banyak tidak akan mempengaruhi proses perkecambahan", "C. laju penguapan tanaman pot A lebih tinggi sehingga kecambah dapat tumbuh","D. kadar air yang terlalu banyak pada pot B membuat biji mengalami pembusukan",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BIOLOGI","Mikroorganisme yang digunakan dalam proses bioteknologi harus memiliki sifat-sifat tertentu, di antaranya....","A. menghasilkan produk yang bersifat alergen","B. merupakan mikroba patogen yang membahayakan", "C. tidak menghasilkan racun atau toksin sampingan yang berbahaya","D. memiliki produktivitas yang tinggi serta sifat yang mudah dikendalikan",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BIOLOGI","Pada usia 5 hari, berat buah semangka adalah 5 kg. Pada usia 10 hari, berat semangka menjadi 15 kg. Namun pada usia 15 hari, berat semangka tetap 15 kg. Penafsiran dari data perkembangan tersebut adalah…","A. pada usia 15 hari tercapai berat tertinggi","B. setelah usia 5 hari, berat buah terus bertambah dengan rata- rata pertambahan 2 kg/hari", "C. semakin bertambah usia, berat buah semakin bertambah pula","D. energi dapat tertimbun dalam bentuk jaringan tubuh",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BAHASA INDONESIA","Bacalah paragraf berikut dengan saksama!\n" + "\n" + "Sebaiknya, brokoli dimasak atau direbus dengan air mendidih dalam kondisi setengah matang. Tambahkan garam untuk membunuh kuman, lalu tiriskan sebentar! Siram dengan air dingin! Fungsi air dingin untuk mempertahankan warna dan memperlambat proses pemasakan brokoli. Dalam kondisi seperti ini, brokoli dapat disimpan 2—3 hari dalam lemari pendingin dan aman dikonsumsi.\n" + "\n" + "Ide pokok paragraf tersebut adalah....","A. cara menyimpan brokoli","B. fungsi garam dan penirisan brokoli", "C. cara mempertahankan warna brokoli","D. daya tahan brokoli" ,R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BAHASA INDONESIA","Setelah dilakukan penilaian terhadap ulangan Bahasa Indonesia kelas XII IPA, yang memperoleh nilai 8 sebanyak 25 orang, nilai 7 sebanyak 4 orang, dan nilai 6 hanya 1 orang. Jumlah siswa 30 orang. (...)\n" + "\n" + "Simpulan yang tepat untuk mengakhiri paragraf tersebut adalah....","A. Belum dapat dikatakan mereka pintar.","B. Mereka belum dikatakan siswa yang pandai.", "C. Dapat dikatakan nilai mereka baik.","D. Jadi, guru mereka boleh berbangga.",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BAHASA INDONESIA","Kami turut prihatin kepada terjadinya musibah di daerah itu.\n" + "\n" + "Kalimat efektif hasil perbaikan kalimat tersebut yang tepat adalah....","A. Kami turut prihatin sehingga terjadinya musibah di daerah itu.","B. Kami turut prihatin maka terjadinya musibah di daerah itu.", "C. Kami turut prihatin dari terjadinya musibah di daerah itu.","D. Kami turut prihatin atas terjadinya musibah di daerah itu.",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BAHASA INDONESIA","Janganlah sampai kawan\n" + "\n" + "Kesejahteraan tinggallah angan\n" + "\n" + "Keadilan hanyalah khayal\n" + "\n" + "Kemerdekaan kembalilah terjajah\n" + "\n" + "Yang tersisa hanyalah kebodohan\n" + "\n" + " \n" + "\n" + "Mari naik kapal, kawan\n" + "\n" + "Jangan hanya tinggal diam\n" + "\n" + "Mari bersatu ambil peranan\n" + "\n" + "Buatlah perubahan\n" + "\n" + " \n" + "\n" + "Kata naik kapal dalam puisi tersebut melambangkan....","A. melakukan perjuangan","B. memberikan kesempatan", "C. menunjukkan ketakutan","D. melakukan pembangunan",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BAHASA INDONESIA","Sani seseorang siswa baru di kelas kami. Anaknya pendiam, tetapi murah senyum. Melihat penampilan dia yang banyak diam, banyak teman mengira Sani seorang siswa biasa-biasa saja. Akan tetapi, pada saat ulangan dan hasilnya diumumkan, nilai Sani selalu yang tertinggi. Seperti kata peribahasa ....\n" + "\n" + "Peribahasa yang sesuai dengan ilustrasi tersebut adalah....","A. air yang tenang menghanyutkan","B. memikul di bahu, memikul di kepala", "C. seperti ilmu padi, kian berisi, kian merunduk","D. pikir itu pelita hatiair beriak tanda tak dalam",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BAHASA INGGRIS","My first time experience in Bali\n" + "\n" + "At 55 I have just gone to Bali for the first time with my husband. We stayed in Seminyak and had a wonderful time. We took Jetstar in economy over and were in 2nd last row and even then by time off plane purchasing VOA and Immigration took about 1 hour - wasn't too bad. Departing last night, Jetstar was late by one hour but we had paid to go Business class so it was not that bad. We sat in Premier Lounge - not a great selection of food or wine (wine is my thing) but it was enjoyable anyway. Of course, new airport is underway and things may be different once that is up and running. We didn't get sick or robbed or bitten. Yes, footpaths are broken and or missing and some smells but that didn't 16deter us. People were friendly and so polite. The weather was just fantastic. When asked to take what looked like post cards we politely said \"no thank you \" and that was the last of it. Bintang beer mostly $2.50 very cheap and was the food and we ate in good restaurants - La Lucciola, Breeze, Sardine, Sarong and Metis. As we had breakfast supplied at The Samaya we didn't need lunch and we were given fruit salad by the pool and afternoon tea so only dinner was required. We enjoyed Sarong in particular. We used hand sanitizer and luckily for us we didn't get the dreaded dire - rear. A driver took us to Ubud and Jimbaran Bay and through Kuta. Mostly this was a relaxing one week there. Manicures, pedicures, hair, massage were so cheap - roughly $8 - we had these done at Body Works in Seminyak. I also had Wendy the dressmaker come to our hotel and made me skirts which I was very happy with. This morning in Sydney airport, it took us just 30 minutes to be off the plane and into a taxi. Jetstar made up time flying home - only 5 hours and 10 minutes. It was all a breeze. Bali had never been on my to do list, but I will be going back that is for sure.\n" + "\n" + "Sumber: https://www.tripadvisor.com\n" + "\n" + "What happened when they were about to leave for Bali?","A. They needed to cancel their trip.","B. They needed to put their trip off.", "C. The plane crashed.","D. The plane was late for an hour.",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BAHASA INGGRIS","What is the purpose of the text above?\n","A. To describe what the PayPal website is","B. To give a brief hint how to use PayPal credit", "C. To explain how to register a new bank account","D. To explain how to create a PayPal account",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BAHASA INGGRIS","The sentence ‘You can create an account from the PayPal homepage or from the app.’ could possibly restated as…","A. You need to create an account with both the PayPal homepage and the app.","B. You can make an account either from the PayPal homepage or the app.", "C. You don’t need to create an account from the PayPal homepage or from the app.","D. You are obliged to create an account on the PayPal homepage and the app.",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BAHASA INGGRIS","What is the topic of the passage above?","A. TV isn’t good for children.","B. TV isn’t educational enough for children.", "C. Books are better for children.","D. Books and TV aren’t good for children.",R.drawable.soal_otak));
          IstContact.add(new ModelSoal("BAHASA INGGRIS","1. Anies Rasyid Baswedan was born on 7 May 1969.\n" + "\n" + "2. He was also a rector of a private university before being appointed as a minister.\n" + "\n" + "3. He is an Indonesian academic, activist, and politician.\n" + "\n" + "4. Before being a governor, he served as Minister of Education and Culture.\n" + "\n" + "5. He has currently served as Governor of Jakarta since October 2017.\n" + "\n" + "Sumber: https://en.wikipedia.org\n" + "\n" + " \n" + "\n" + "Arrange the sentences above based on the appropriate procedural text….","A. 1 – 3 – 5 – 4 – 2","B. 1 – 3 – 5 – 2 – 4", "C. 1 – 3 – 4 – 5 – 2","D. 3 – 1 – 5 – 4 – 2",R.drawable.soal_otak));

     }
}
